export const LocationAction = {
  UPDATE_LOCATIONS: "UPDATE_LOCATIONS",
  RECEIVE_LOCATIONS: "RECEIVE_LOCATIONS",
  RECEIVE_SELECTED_LOCATION: "RECEIVE_SELECTED_LOCATION"
};

export const LocationDropdownAction = {
  RECEIVE_SELECTED_LOCATION_DROPDOWN: "RECEIVE_SELECTED_LOCATION_DROPDOWN",
  RECEIVE_LOCATION_DROPDOWN: "RECEIVE_LOCATION_DROPDOWN",
  RESET_DROPDOWN: "RESET_DROPDOWN"
};
