export const PriceServiceTimeAction = {
  REQUEST_FTECH_LEVEL_DATA: "REQUEST_FTECH_LEVEL_DATA",
  RECEIVE_FTECH_LEVEL_DATA_RESULT: "RECEIVE_FTECH_LEVEL_DATA_RESULT",
  RECEIVE_FTECH_LEVEL_DATA_ERROR: "RECEIVE_FTECH_LEVEL_DATA_ERROR",

  REQUEST_FTECH_LEVEL_DATA_BY_PARENT: "REQUEST_FTECH_LEVEL_DATA_BY_PARENT",
  RECEIVE_FTECH_LEVEL_DATA_RESULT_BY_PARENT: "RECEIVE_FTECH_LEVEL_DATA_RESULT_BY_PARENT",
  RECEIVE_FTECH_LEVEL_DATA_ERROR_BY_PARENT: "RECEIVE_FTECH_LEVEL_DATA_ERROR_BY_PARENT",
  
  POST_LEVEL_DATA: "POST_LEVEL_DATA",
  POST_LEVEL_DATA_RESULT: "POST_LEVEL_DATA_RESULT",  
  POST_LEVEL_DATA_ERROR: "POST_LEVEL_DATA_ERROR",  
  PUT_LEVEL_DATA: "PUT_LEVEL_DATA",
  PUT_LEVEL_DATA_RESULT: "PUT_LEVEL_DATA_RESULT",
  PUT_LEVEL_DATA_ERROR: "PUT_LEVEL_DATA_ERROR",  
  DELETE_LEVEL_DATA: "DELETE_LEVEL_DATA",
  DELETE_LEVEL_DATA_RESULT: "DELETE_LEVEL_DATA_RESULT",
  DELETE_LEVEL_DATA_ERROR: "DELETE_LEVEL_DATA_ERROR"
};
