export const UserAction = {
  UPDATE_USER_INFORMATION: "UPDATE_USER_INFORMATION"
};

export const AdminUserAction = {
  GET_ADMIN_USERS: "GET_ADMIN_USERS",
  RECEIVE_ADMIN_USERS: "RECEIVE_ADMIN_USERS",
  GET_COURIERS: "GET_COURIERS",
  RECEIVE_COURIERS: "RECEIVE_COURIERS"
};
